/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Text, useFont, useGLTF, useTexture } from "@react-three/drei";

// const CARD_DESCRIPTIONS = {
//   punch: "攻击另外一个海盗，使其掉落宝石",
//   grab: "掠夺宝石，如果没有宝石，你什么也无法得到",
//   shield: "躲进桶子里，使自己免受攻击",
// };
const CARD_DESCRIPTIONS = {
  punch: "Attack another pirate and make him drop gems",
  grab: "Plunder gems. If you don't have gems, you get nothing",
  shield: "Hide in the barrel to protect yourself from attack",
};
export function Card({ type = "shield", ...props }) {
  const { nodes, materials } = useGLTF("/models/card.glb");
  const texture = useTexture(`cards/${type}.jpg`);

  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry}>
        <meshStandardMaterial
          {...materials.Front}
          map={texture}
          color={"white"}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials.Borders}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials.Back}
      />
      <Text
        font="/fonts/RobotoSlab-Bold.ttf"
        fontSize={0.1}
        anchorY={"top"}
        anchorX={"left"}
        position={[-0.46, -0.3, 0.01]}
      >
        {type.toUpperCase()}
        <meshStandardMaterial
          roughness={materials.Front.roughness}
          color={"white"}
        />
      </Text>
      <Text
        font="/fonts/RobotoSlab-Regular.ttf"
        fontSize={0.06}
        maxWidth={0.9}
        anchorY={"top"}
        anchorX={"left"}
        position={[-0.46, -0.44, 0.01]}
        lineHeight={1}
      >
        {CARD_DESCRIPTIONS[type] || ""}
        <meshStandardMaterial
          roughness={materials.Front.roughness}
          color={"white"}
        />
      </Text>
    </group>
  );
}

useGLTF.preload("/models/card.glb");
useTexture.preload("/cards/punch.jpg");
useTexture.preload("/cards/shield.jpg");
useTexture.preload("/cards/garb.jpg");

useFont.preload("/fonts/RobotoSlab-Bold.ttf");
useTexture.preload("/fonts/RobotoSlab-Regular.ttf");
